### ISSUE TITLE
Development Board Discontinued

### ISSUE THREAD

**Issue by ssalinasnmt** [bitbane/CANT#4]
The Nucleo-H743ZI dev board has been discontinued or obsoleted by STMicro, as reported on [Digikey](https://www.digikey.com/product-detail/en/stmicroelectronics/NUCLEO-H743ZI/497-17786-ND/7809236), [Arrow](https://www.arrow.com/en/products/nucleo-h743zi/stmicroelectronics) and [Mouser](https://www.mouser.com/ProductDetail/STMicroelectronics/NUCLEO-H743ZI?qs=sGAEpiMZZMtw0nEwywcFgJjuZv55GFNm7ytwN0oIlEPfWPOCd3VVEQ%3D%3D).  

The suggested alternate is the Nucleo-H743ZI2, which appears to be identical form factor, but with different capabilities - specifically, according to the [data sheet](https://www.st.com/resource/en/data_brief/nucleo-h743zi.pdf), the new board supports STLINK-V3E where the original supports ST-LINK/V2-1.  The new board also lacks support for Arm Mbed. I don't believe either of these differences will affect this project, but I'm not entirely sure.

**Comment by bitbane** [comment]
Hey, thanks for the heads up. I'll pick up one of the new Dev boards and
verify, but it looks like it should Just Work(tm). (Famous last words)

**Comment by bitbane** [comment]
Sorry for the long delay, but the Nucleo-H743ZI2 works just fine out of the box. I'll get the readme updated.

**Comment by mecani** [comment]
sorry to comment a closed issue but the Nucleo-H743ZI2 doesn't work out of the box for me, the  a solder had to be done on the sb7 path on the bottom side. My version is slightly different, I have the MB1364-h743zi-c01 and MB1364C instead of MB1364B.
