### ISSUE TITLE
New STM32H743ZI2 BOARD

### ISSUE THREAD

**Issue by plrosa** [bitbane/CANT#5]
Hi we forked your marter repo, we note a couples things.
=> a resistor jumper has to be added on SB7 at the back of the Zi2 board
=> makefile is missing the following line "CFLAGS+=--specs=nosys.specs" at least on Ubuntu 20

Thanks and great job

**Comment by bitbane** [comment]
Thanks for the bug report. I updated the makefile a while ago, that was a change with newer versions of the arm compiler so thanks for that. The SB7 resistor according to the datasheet (https://www.st.com/resource/en/user_manual/um2407-stm32h7-nucleo144-boards-mb1364-stmicroelectronics.pdf) is for the usart3 virtual com port, which I am not using, and I've successfully run CANT on several ZI2 boards without modification.

**Comment by bitbane** [comment]
So I just found out that this is a problem specifically with the MB1364C (and possibly D?) revision of the H743ZI2 board. I'll uodate the readme with that note.
